name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install SFDX CLI and sfdx-git-delta plugin # Ce package va vous permettre de faire un delta entre votre branche et la branch ciblé. Voici la documentation : https://github.com/scolladon/sfdx-git-delta
        run: |
          npm install -g @salesforce/cli@latest
          echo "y" | sf plugins install sfdx-git-delta@latest

      - name: 'Authentification Salesforce' # Vous devez avoir une connexion avec Salesforce pour pouvoir deployer le code à la dernière étape.
        run: |
          echo "${{ secrets.JWT_SECRET_KEY }}" > server.key
          sf org login jwt --client-id ${{ secrets.CONSUMER_KEY }} --jwt-key-file server.key --username ${{ secrets.USERNAME }} --instance-url https://login.salesforce.com --set-default

      - name: 'Generate metadata delta pull request'  # Utilisez le plug-in sfdx-git-delta pour effectuer un delta, generer le package xml dans un fichier temporaire ex : .temp
        run: | # A faire
          sf sgd source delta -r . --to "HEAD" --from "HEAD~1" -o . -i .sgdignore

      - name: 'Déployer les métadonnées sur la branch main'
        if: github.ref == 'refs/heads/main'
        run: | # A faire déployer le code venant du fichier package.xml généré précédemment
          sf project deploy start -x package/package.xml -l RunLocalTests --post-destructive-changes destructiveChanges/destructiveChanges.xml --wait 30
